name: Docker Image CI

on:
  push:

env:
  ALIYUN_IMAGE_TOKEN: ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build the docker image
        run: |
          docker build -t yansongda/rust-jieba .
      - name: Tag the image
        run: |
          docker tag yansongda/php-fpm registry.cn-shenzhen.aliyuncs.com/yansongda-app/rust-jieba
      - name: Push the image to aliyun registry
        run: |
          docker login --username=me@yansongda.cn registry.cn-shenzhen.aliyuncs.com -p ${{ secrets.ALIYUN_IMAGE_ACCESSTOKEN }}
          docker push registry.cn-shenzhen.aliyuncs.com/yansongda-app/rust-jieba